- hosts: all
  become: yes
  tasks:
    - name: Install httpd service
      yum:
        name: httpd
        state: present
        update_cache: yes

    - name: Start httpd service
      service:
        name: httpd
        state: started
        enabled: true
